import type { Metadata } from "next";
// import "../globals.css";
import { Cairo, Poppins } from "next/font/google";
import { hasLocale, NextIntlClientProvider } from "next-intl";
import { notFound } from "next/navigation";
import LayoutProvider from "../components/LayoutProvider";
import { routing } from "@/i18n/routing";
import Providers from "../components/providers";
import { makeStore, AppStore } from '../store/store'
import { Provider } from "react-redux";
import { useRef } from "react";

const PoppinsFont = Poppins({
  variable: "--font-pp",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});
const arabicFont = Cairo({
  variable: "--font-ar",
  subsets: ["arabic"],
});

export const metadata: Metadata = {
  title: "Massar Dashboard",
  description: "Generated by create next app",
  icons: {
    icon: "/file.svg",
  },
};

export default async function RootLayout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: { locale: string };
}) {
  const { locale } = await params;
  if (!hasLocale(routing.locales, locale)) {
    notFound();
  }
  const messages = (await import(`../../messages/${locale}.json`)).default;

    // eslint-disable-next-line react-hooks/rules-of-hooks
    const storeRef = useRef<AppStore>(undefined)
  if (!storeRef.current) {
    // Create the store instance the first time this renders
    storeRef.current = makeStore()
  }

  return (
    <html className="dark" lang={locale} dir={hasLocale(["ar"], locale) ? "rtl" : "ltr"}>

      <body
        className={`
    ${PoppinsFont.variable}
    ${arabicFont.variable}
    antialiased 
  `}
      >
        <NextIntlClientProvider messages={messages || {}}>
          <Provider store={storeRef.current}>
            <Providers >
              <LayoutProvider>
                <main className="grow flex flex-col  w-full " >
                  {children}
                </main>
              </LayoutProvider>
            </Providers>
          </Provider>
        </NextIntlClientProvider>

      </body>
    </html >
  );
}
